{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-configmap
  labels:
    {{- include "microservice.metadataLabels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.data | nindent 2 }}
{{- end }}